version: "3"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nik
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/data/pgdata
