CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE todo (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  task_name VARCHAR (50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
)